### ISSUE TITLE
[RFC] Storage of join section data

### ISSUE THREAD

**Issue by RitikJaiswal75** [Real-Dev-Squad/website-www#286]
## Problem Description
Once the user enters his/her details in the join section a personalized link is created for them to share with the verifier. This link contains their data. The **Issue** here is whether to store the data after verification of the user or as soon as the user submits the form.

## Current flow
- user signs in using the GitHub login.
- redirected to new signup flow by @vinayak-trivedi 
- after the signup flow user is sent to the join section to enter the details.
- a user-specific link is generated which has his/her data.
- link shared to the verifier to verify and send the discord invite link.

**Note:** The issue is to store the data before verification or after verification.

**Comment by RitikJaiswal75** [comment]
Based on the current flow I am planning to save the user progress in the join section in local storage

**Comment by RitikJaiswal75** [comment]
data gets saved in a temporary place after submission. update in firestore after approval.

**Comment by vinayak-trivedi** [comment]
I think we should store the data of the user once he completes the join section form, one question I've is that is there a way that we delete some data after a particular number of days, there are some data that we may not need after @ankushdharkar sees those responses

**Comment by rohan09-raj** [comment]
- What is the scenario when the data remains unverified? How it is conveyed that the verification request is rejected?
- And does the user has to go through the same form again if the request is rejected?
- In this case, we maybe need the previous data to prefill the data to have better UX.
- Instead of storing in local storage, I prefer to go with @vinayak-trivedi 's suggestion, we can set some expiry of the unverified data, and after that amount of time, it gets deleted if it's still not verified.
- Also, local storage will be limited to the browser only, suppose a user changes their browser then they won't get their previous info they have filled.
- But building that mechanism may take time.

**Comment by prakashchoudhary07** [comment]
I would want to know what is a verification process, what happens in verification, and how is the verification process done. Want more details on this to get more context on it? What data would be required for the verification process?

But with what I am able to interpret, I think user data should be stored in the DB before the verification process, As Verification, process can take some time, and during that period there is a possibility of data loss if stored in the user's browser without backup

**Comment by Maheima** [comment]
can we have a diagrammatic representation of flow? What is the payload?

**Comment by RitikJaiswal75** [comment]
As per the discussion with @ankushdharkar on the hangout call on 20 September 2022, 9:40 PM IST. we will be using local storage to save data.

**Comment by prakashchoudhary07** [comment]
And what was the reason that led to that, Will be helpful if you can provide some details of why this was chosen and why not the other options.
