### ISSUE TITLE
[RFC] Ember.js or Next.js(React) for realdevsquad.com

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-www#8]
We need to select a framework going forward, and I have two strong contenders in mind for it

**Comment by invalidtoken** [comment]
I haven't used Ember yet but I use next.js daily in my day job. Here are some things that I like about next.js
 
1. Next.js provides pre-defined Webpack config and support CSS, Typescript, route/component-based code-splitting, styled JS(their version of CSS-in-JS), AMP, out of the box. Not sure if ember.js also supports this. 
2. Next.js also provides packages for adding LESS, SASS which are built by the same team so they can be added super easily. 
3. I find routing in next.js fairly easy and straight-forward. 

Things that I think we should consider - 
1. Next.js is a react based SSR framework, more people know react then ember, which means more people can contribute to the website fairly easily. 
2. If we choose ember then it will be a new framework for a lot of people. Which is also a really good thing. 
3. Which framework has better documentation and dev community? 
4. Which framework has more number of resolved Github/StackOverflow issues? 


Note I didn't mention topics like ease of use, choice of language, quality of documentation, etc because I haven't worked with both the frameworks. Also, I find them very subjective. 

It would be great if someone who has worked with both Ember and Next.js can state some points.

**Comment by shihabus** [comment]
I haven't tried Ember.js so far, but would love to do it for sake of learning. I guess this can be a great opportunity to learn. Since this a community effort, we wouldn't have hard to miss deadlines (I hope). If that is the case, I would vote for something less tried out, relatively new and prospective.

**Comment by bishal007** [comment]
I never used Ember.js, but looking forward to seeing the scope and potential of this framework in particular. Hope will get hands dirty and try out experiments.

**Comment by sumitd94** [comment]
I feel we should go with Ember JS.
The reason is, many of us here know react and ember seems new to many people and if we go with ember .. we all will be at same level and this way we can help each other and move forward with learning.

**Comment by rohan09-raj** [comment]
Conclusion: We are building my-site which is in EmberJS that will consume this home page and eventually my-site will become the home page for Real Dev Squad in future.
